[package]
name = "egomoose/buffer-stream"
description = "An abstraction for buffers that allows reading and writing data in sequence."
repository = "https://github.com/EgoMoose/rbx-buffer-stream"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"